### ISSUE TITLE
Server gives up restarting after several syntax errors

### ISSUE THREAD

**Issue by a-mckinley** [UniqueVision/plpgsql-lsp#13]
## Describe the bug

During development of some new code, the server restarts on syntax errors in the incomplete code, and eventually doesn't restart again.

Here is an example log message in the plpgsql-lsp output.

```
[Error - 12:41:30] SyntaxError code: 42601, error: syntax error at or near ")"
The file definitions are updating...
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: syntax error at or near ")"] {
  fileName: 'scan.l',
  functionName: 'scanner_yyerror',
  lineNumber: 1230,
  cursorPosition: 2515,
  context: null
}
[Error - 12:41:30] Connection to server got closed. Server will not be restarted.
```

## Expected Behavior

I believe the server should continue to operate or restart if the errors are merely syntax errors.

## Current Behavior

After a few syntax errors are submitted to postgresql within a certain time period, the server does not restart again.

## Steps to Reproduce

Write a new SQL file, stop typing when the code is incomplete several times until the server does not restart again.

## Environment

plpgsql-lsp v2.2.1 and vscode 1.66.0 on Linux.

**Comment by yassun4dev** [comment]
Thanks for the report.

Fixed and [v2.2.2](https://github.com/UniqueVision/plpgsql-lsp/tree/v2.2.2) is now available.

**Comment by a-mckinley** [comment]
Hi @yassun4dev .

Thanks for looking at this.

I am still seeing this issue on v2.2.2, although it seems to be less frequently triggered.

For example

```
[Error - 10:55:23] SyntaxError code: 42601, error: syntax error at or near "rollback"
The file definitions are updating...
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: syntax error at or near "rollback"] {
  fileName: 'scan.l',
  functionName: 'scanner_yyerror',
  lineNumber: 1230,
  cursorPosition: 4338,
  context: null
}
[Error - 10:55:23] Connection to server got closed. Server will not be restarted.
```

**Comment by yassun4dev** [comment]
@a-mckinley

Your report has been helpful.

I fixed more code and release [v2.2.3](https://github.com/UniqueVision/plpgsql-lsp/tree/v2.2.3).

As far as I can know there are no errors, but unfortunately I am not working by using SQL for the current project, so I can't be sure.

If you still encounter the error, please report them to us.

Thanks !
